-- Indexes generated from schema CSV

CREATE INDEX idx_age_verifications_customer_id_fkhelper ON public.age_verifications USING btree (customer_id);
CREATE INDEX idx_age_verifications_verified_by_fk ON public.age_verifications USING btree (verified_by);
CREATE INDEX idx_analytics_events_user_id_fkhelper ON public.analytics_events USING btree (user_id);
CREATE INDEX idx_audit_logs_created_at ON public.audit_logs USING btree (created_at DESC);
CREATE INDEX idx_audit_logs_record_id ON public.audit_logs USING btree (record_id);
CREATE INDEX idx_audit_logs_user_created ON public.audit_logs USING btree (user_id, created_at DESC);
CREATE INDEX idx_audit_logs_user_id_fkhelper ON public.audit_logs USING btree (user_id);
CREATE INDEX idx_automation_workflows_created_by_fk ON public.automation_workflows USING btree (created_by);
CREATE INDEX idx_bookings_booking_date ON public.bookings USING btree (booking_date);
CREATE INDEX idx_bookings_created_by ON public.bookings USING btree (created_by);
CREATE INDEX idx_bookings_customer_id ON public.bookings USING btree (customer_id);
CREATE INDEX idx_bookings_customer_id_fkhelper ON public.bookings USING btree (customer_id);
CREATE INDEX idx_bookings_deleted_at ON public.bookings USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_bookings_location_id ON public.bookings USING btree (location_id) WHERE (location_id IS NOT NULL);
CREATE INDEX idx_bookings_table_id ON public.bookings USING btree (table_id) WHERE (table_id IS NOT NULL);
CREATE INDEX idx_campaign_analytics_campaign_id_fkhelper ON public.campaign_analytics USING btree (campaign_id);
CREATE INDEX idx_campaign_templates_created_by_fk ON public.campaign_templates USING btree (created_by);
CREATE INDEX compliance_retention_runs_created_at_idx ON public.compliance_retention_runs USING btree (created_at DESC);
CREATE INDEX idx_customer_memberships_customer ON public.customer_memberships USING btree (customer_id);
CREATE INDEX idx_customers_deleted_at ON public.customers USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_customers_email ON public.customers USING btree (email);
CREATE INDEX idx_customers_name ON public.customers USING btree (name);
CREATE INDEX idx_customers_profile_id ON public.customers USING btree (profile_id);
CREATE INDEX idx_email_campaigns_created_by_fk ON public.email_campaigns USING btree (created_by);
CREATE INDEX idx_email_campaigns_customer_id_fkhelper ON public.email_campaigns USING btree (customer_id);
CREATE INDEX idx_enhanced_rewards_claimed_by_staff_id_fk ON public.enhanced_rewards USING btree (claimed_by_staff_id);
CREATE INDEX idx_enhanced_rewards_customer_id_fkhelper ON public.enhanced_rewards USING btree (customer_id);
CREATE INDEX idx_event_templates_created_by_fk ON public.event_templates USING btree (created_by);
CREATE INDEX idx_events_created_by_fk ON public.events USING btree (created_by);
CREATE INDEX idx_events_deleted_at ON public.events USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_events_location_event_date ON public.events USING btree (location_id, event_date DESC);
CREATE INDEX idx_feedback_customer_id_fkhelper ON public.feedback USING btree (customer_id);
CREATE INDEX idx_feedback_deleted_at ON public.feedback USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_feedback_visit_id_fk ON public.feedback USING btree (visit_id);
CREATE INDEX idx_financial_transactions_created_by_fk ON public.financial_transactions USING btree (created_by);
CREATE INDEX idx_financial_transactions_reporting ON public.financial_transactions USING btree (transaction_date DESC, transaction_type);
CREATE INDEX floor_sections_location_id_idx ON public.floor_sections USING btree (location_id);
CREATE INDEX idx_gift_cards_status ON public.gift_cards USING btree (status);
CREATE INDEX idx_google_review_prompts_customer_id_fkhelper ON public.google_review_prompts USING btree (customer_id);
CREATE INDEX idx_google_review_prompts_visit_id_fk ON public.google_review_prompts USING btree (visit_id);
CREATE INDEX idx_google_reviews_customer_id_fkhelper ON public.google_reviews USING btree (customer_id);
CREATE INDEX idx_google_reviews_visit_id_fk ON public.google_reviews USING btree (visit_id);
CREATE INDEX idx_inventory_active ON public.inventory USING btree (is_active);
CREATE INDEX idx_inventory_category ON public.inventory USING btree (category);
CREATE INDEX idx_inventory_created_by_fk ON public.inventory USING btree (created_by);
CREATE INDEX idx_inventory_deleted_at ON public.inventory USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_inventory_location_id ON public.inventory USING btree (location_id);
CREATE INDEX idx_invitation_codes_created_by_fk ON public.invitation_codes USING btree (created_by);
CREATE INDEX idx_invitation_codes_used_by_fk ON public.invitation_codes USING btree (used_by);
CREATE INDEX idx_logs_inventory_action ON public.logs_inventory USING btree (action);
CREATE INDEX idx_logs_inventory_date ON public.logs_inventory USING btree (created_at);
CREATE INDEX idx_logs_inventory_inventory ON public.logs_inventory USING btree (inventory_id);
CREATE INDEX idx_logs_inventory_performed_by_fk ON public.logs_inventory USING btree (performed_by);
CREATE INDEX idx_loyalty_alcohol_punch ON public.loyalty USING btree (alcohol_punch_count);
CREATE INDEX idx_loyalty_coffee_punch ON public.loyalty USING btree (coffee_punch_count);
CREATE INDEX idx_loyalty_customer_id_fkhelper ON public.loyalty USING btree (customer_id);
CREATE INDEX idx_loyalty_rewards_loyalty_id_fkhelper ON public.loyalty_rewards USING btree (loyalty_id);
CREATE INDEX idx_marketing_campaigns_created_by_fk ON public.marketing_campaigns USING btree (created_by);
CREATE INDEX idx_marketing_emails_campaign_id_fkhelper ON public.marketing_emails USING btree (campaign_id);
CREATE INDEX idx_marketing_emails_customer_id_fk ON public.marketing_emails USING btree (customer_id);
CREATE INDEX idx_menu_categories_name ON public.menu_categories USING btree (name);
CREATE INDEX idx_menu_item_modifiers_modifier ON public.menu_item_modifiers USING btree (modifier_id);
CREATE INDEX idx_menu_item_tags_item ON public.menu_item_tags USING btree (menu_item_id);
CREATE INDEX idx_menu_item_tags_tag ON public.menu_item_tags USING btree (tag_id);
CREATE INDEX idx_menu_items_available ON public.menu_items USING btree (is_available);
CREATE INDEX idx_menu_items_category ON public.menu_items USING btree (category);
CREATE INDEX idx_menu_items_created_by_fkhelper ON public.menu_items USING btree (created_by);
CREATE INDEX idx_menu_items_eighty_sixed ON public.menu_items USING btree (is_eighty_sixed) WHERE (is_eighty_sixed = true);
CREATE INDEX idx_menu_subcategories_category ON public.menu_subcategories USING btree (category_id);
CREATE INDEX idx_newsletters_created_by_fk ON public.newsletters USING btree (created_by);
CREATE INDEX idx_notifications_user_id_fkhelper ON public.notifications USING btree (user_id);
CREATE INDEX idx_offline_sync_batches_status ON public.offline_sync_batches USING btree (status);
CREATE INDEX idx_order_events_order_created ON public.order_events USING btree (order_id, created_at DESC);
CREATE INDEX idx_orders_location_created ON public.orders USING btree (location_id, opened_at DESC);
CREATE INDEX idx_payment_transactions_customer_id_fkhelper ON public.payment_transactions USING btree (customer_id);
CREATE INDEX idx_pricing_windows_location ON public.pricing_windows USING btree (location_id);
CREATE INDEX idx_profiles_email ON public.profiles USING btree (email);
CREATE INDEX idx_profiles_role ON public.profiles USING btree (role);
CREATE INDEX idx_profiles_user_id ON public.profiles USING btree (user_id);
CREATE INDEX idx_promotional_materials_created_by_fk ON public.promotional_materials USING btree (created_by);
CREATE INDEX idx_promotions_created_by_fk ON public.promotions USING btree (created_by);
CREATE INDEX idx_purchase_orders_location_ordered ON public.purchase_orders USING btree (location_id, ordered_at DESC);
CREATE INDEX idx_push_subscriptions_profile_id ON public.push_subscriptions USING btree (profile_id);
CREATE INDEX idx_referrals_deleted_at ON public.referrals USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_referrals_referrer_id_fkhelper ON public.referrals USING btree (referrer_id);
CREATE INDEX idx_rewards_claimed_by_staff_id_fk ON public.rewards USING btree (claimed_by_staff_id);
CREATE INDEX idx_rewards_customer_id_fkhelper ON public.rewards USING btree (customer_id);
CREATE INDEX idx_rsvps_customer_id_fk ON public.rsvps USING btree (customer_id);
CREATE INDEX idx_sales_receipts_order ON public.sales_receipts USING btree (order_id);
CREATE INDEX idx_shifts_staff_id_fkhelper ON public.shifts USING btree (staff_id);
CREATE INDEX idx_social_posts_created_by_fk ON public.social_posts USING btree (created_by);
CREATE INDEX idx_social_posts_platform ON public.social_posts USING btree (platform);
CREATE INDEX idx_social_posts_posted_at ON public.social_posts USING btree (posted_at DESC);
CREATE INDEX idx_social_posts_status_scheduled_at ON public.social_posts USING btree (status, scheduled_at);
CREATE INDEX idx_staff_deleted_at ON public.staff USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_staff_position ON public.staff USING btree ("position");
CREATE INDEX idx_staff_profile_id ON public.staff USING btree (profile_id);
CREATE INDEX idx_staff_user_id_fk ON public.staff USING btree (user_id);
CREATE INDEX idx_staff_break_logs_attendance ON public.staff_break_logs USING btree (attendance_log_id);
CREATE INDEX idx_staff_performance_staff_id_fkhelper ON public.staff_performance USING btree (staff_id);
CREATE INDEX idx_staff_schedules_staff_id_fkhelper ON public.staff_schedules USING btree (staff_id);
CREATE INDEX idx_stock_movements_inventory_created ON public.stock_movements USING btree (inventory_id, created_at DESC);
CREATE INDEX idx_tasks_assigned_by_fk ON public.tasks USING btree (assigned_by);
CREATE INDEX idx_tasks_assigned_to_fkhelper ON public.tasks USING btree (assigned_to);
CREATE INDEX idx_tasks_category ON public.tasks USING btree (category);
CREATE INDEX idx_tasks_created_by ON public.tasks USING btree (created_by);
CREATE INDEX idx_tasks_deleted_at ON public.tasks USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_tasks_related_event ON public.tasks USING btree (related_event_id);
CREATE INDEX idx_tasks_tags ON public.tasks USING gin (tags);
CREATE INDEX idx_visit_milestones_customer_id_fkhelper ON public.visit_milestones USING btree (customer_id);
CREATE INDEX idx_visit_qr_codes_visit_id_fkhelper ON public.visit_qr_codes USING btree (visit_id);
CREATE INDEX idx_visits_customer_id_fkhelper ON public.visits USING btree (customer_id);
CREATE INDEX idx_visits_deleted_at ON public.visits USING btree (deleted_at) WHERE (deleted_at IS NULL);
CREATE INDEX idx_visits_staff_id_fkhelper ON public.visits USING btree (staff_id);
CREATE INDEX idx_waitlist_created_by_fk ON public.waitlist USING btree (created_by);
CREATE INDEX idx_waitlist_date_priority_rank ON public.waitlist USING btree (date, priority_rank, created_at);
